version: "2"

services:

  ghost:
    restart: always
    expose:
      - 2368
    environment:
      NODE_ENV: production
      url: https://${DOMAIN_NAME}

  nginx:
    build: ./nginx
    container_name: ${NGINX_CONTAINER_NAME}
    restart: always
    depends_on:
      - ghost
    volumes:
      - ./nginx/ghost.conf/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - ${NGINX_HTML_PATH}:/var/www/html
    ports:
      - 80:80
      - 443:443

