version: "3"

services:

  nginx-proxy:
    build:
      context: ./nginx
      dockerfile: ./proxy/Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx-conf:/etc/nginx/conf.d
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - nginx-certs:/etc/nginx/certs:ro
      - nginx-htpasswd:/etc/nginx/htpasswd:ro

  docker-gen:
    build:
      context: ./nginx
      dockerfile: ./gen/Dockerfile
    restart: always
    volumes:
      - nginx-conf:/etc/nginx/conf.d
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - nginx-certs:/etc/nginx/certs:ro
      - nginx-htpasswd:/etc/nginx/htpasswd:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro,z
    command: >
      -notify-sighup nginx-proxy \
      -watch -wait 5s:30s \
      /etc/docker-gen/templates/nginx.tmpl \
      /etc/nginx/conf.d/default.conf

  nginx-ssl:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - nginx-certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
      NGINX_DOCKER_GEN_CONTAINER: docker-gen

  ghost:
    restart: always
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: ${DOMAIN_NAME}
      LETSENCRYPT_HOST: ${DOMAIN_NAME}
      LETSENCRYPT_EMAIL: ${ADMIN_EMAIL}
      url: https://${DOMAIN_NAME}

  cron:
    build: ./cron
    restart: always
    depends_on:
      - ghost
    volumes:
      - ghost-data:/usr/share/ghost_data
      - ghost-backup:/usr/share/ghost_backup
    environment:
      DATA_PATH: /usr/share/blog_data
      BACKUP_PATH: /usr/share/blog_backup

volumes:
  nginx-conf:
  nginx-vhost:
  nginx-html:
  nginx-certs:
  nginx-htpasswd:
  ghost-backup:

