version: "3"

services:

  nginx_proxy:
    build:
      context: ./nginx
      dockerfile: ./proxy/Dockerfile
    restart: always
    ports:
      - "80:80"
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - nginx_certs:/etc/nginx/certs:ro
      - nginx_htpasswd:/etc/nginx/htpasswd:ro

  docker_gen:
    build:
      context: ./nginx
      dockerfile: ./gen/Dockerfile
    restart: always
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - nginx_certs:/etc/nginx/certs:ro
      - nginx_htpasswd:/etc/nginx/htpasswd:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro,z
    command: -notify-sighup nginx_proxy -watch -only-exposed /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  ghost:
    restart: always
    environment:
      VIRTUAL_HOST: ${DOMAIN_NAME}
      NODE_ENV: production
      url: https://${DOMAIN_NAME}

  cron:
    build: ./cron
    restart: always
    depends_on:
      - ghost
    volumes:
      - ghost_data:/usr/share/ghost_data:ro
      - ghost_backup:/usr/share/ghost_backup
    environment:
      DATA_PATH: /usr/share/ghost_data
      BACKUP_PATH: /usr/share/ghost_backup

volumes:
  nginx_conf:
  nginx_vhost:
  nginx_html:
  nginx_certs:
  nginx_htpasswd:
  ghost_backup:

